version: '3.7'

volumes:
    backups:
    web:
networks:
    backups:

services:
    disasterman:
        image: qbitartifacts/disasterman:master
        environment:
            - HEADER_NAME=DisasterMan
            - ADMIN_PASSWORD=admin123
            #- SMTP_SERVER=smtp.gmail.com
            #- SMTP_ENCRYPTION=starttls
            #- SMTP_USERNAME=myuser@example.com
            #- SMTP_PASSWORD=mypassword
        ports:
            - 8080:8080
        volumes:
            - backups:/backups
            - web:/etc/rdiffweb
        networks:
            - backups
        deploy:
            placement:
                constraints:
                    - node.labels.backups == server
    agent:
        image: qbitartifacts/disasterman-agent:master
        environment:
            # scheduled everyday at 4:00AM
            - CRON_SCHEDULE=0 4 * * *
            - SERVER=disasterman
        volumes:
            - /var/lib/docker/volumes:/volumes
        networks:
            - backups
        deploy:
            mode: global
            placement:
                constraints:
                    - node.labels.backups != server
